### ISSUE TITLE
Rendering is broken in windows cmd and powershell

### ISSUE THREAD

**Issue by makeworld-the-better-one** [gookit/color#13]
Using the `.Render` method of `Style`s like `color.New(color.OpItalic, color.OpBold)`, `color.New(color.Cyan)`, or ` color.New(color.BgGray)` doesn't seem to work on Windows. The full code I wrote is [here](https://github.com/makeworld-the-better-one/go-dict), please test it for yourself and let me know if I made a mistake. Is it because I'm using `tabwriter`? The colors work fine on Linux.

**Comment by inhere** [comment]
hi @makeworld-the-better-one 

If you directly use `fmt.Fprintln` on Windows, it will not allow color output to work properly.

Please see how I got him to work here:

https://github.com/gookit/color/blob/4424096b9787fc36df5fd5e15c62886edbf13544/utils.go#L112-L131

https://github.com/gookit/color/blob/4424096b9787fc36df5fd5e15c62886edbf13544/color_windows.go#L169-L188

Maybe you should use `color.Fprintf/color.Fprintln` instead of this `fmt.Fprintf/fmt.Fprintln` method

**Comment by makeworld-the-better-one** [comment]
Oh okay thanks for explaining. I will try that and report back.
